In [7]:
# import all neccessary libs

import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_transformer

In [22]:
# import salary dataset 

salary = pd.read_csv("Salary Data.csv")
salary

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [25]:
# get out dependent and indepenent datasets
x = salary.drop("Salary", axis=1)
y = salary["Salary"]

x.loc[0]

Age                                 32.0
Gender                              Male
Education Level               Bachelor's
Job Title              Software Engineer
Years of Experience                  5.0
Name: 0, dtype: object

In [30]:
# normalize our dataset
tf.random.set_seed(42)
ct = make_column_transformer(
    (MinMaxScaler(), ["Age", "Years of Experience"]),
    (OneHotEncoder(handle_unknown='ignore'), ["Gender", "Education Level", "Job Title"])
)

# split our dataset to test and train
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)

# fit the column transformer to our training dataset
ct.fit(x_train)

# tranforming trainig and test with normaliztion and onhotencoder
x_train_normalize = ct.transform(x_train)
x_test_normalize = ct.transform(x_test)

x_train.loc[0]

KeyError: 0