In [19]:
# import all neccessary libs

import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_transformer

In [39]:
# import salary dataset 

salary = pd.read_csv("Salary Data.csv")
salary = salary.drop("Job Title", axis=1)

salary

      Age  Gender Education Level  Years of Experience    Salary
0    32.0    Male      Bachelor's                  5.0   90000.0
1    28.0  Female        Master's                  3.0   65000.0
2    45.0    Male             PhD                 15.0  150000.0
3    36.0  Female      Bachelor's                  7.0   60000.0
4    52.0    Male        Master's                 20.0  200000.0
..    ...     ...             ...                  ...       ...
370  35.0  Female      Bachelor's                  8.0   85000.0
371  43.0    Male        Master's                 19.0  170000.0
372  29.0  Female      Bachelor's                  2.0   40000.0
373  34.0    Male      Bachelor's                  7.0   90000.0
374  44.0  Female             PhD                 15.0  150000.0

[375 rows x 5 columns]

In [41]:
# get out dependent and indepenent datasets
x = salary.drop("Salary", axis=1)
y = salary["Salary"]

x.head()

    Age  Gender Education Level  Years of Experience
0  32.0    Male      Bachelor's                  5.0
1  28.0  Female        Master's                  3.0
2  45.0    Male             PhD                 15.0
3  36.0  Female      Bachelor's                  7.0
4  52.0    Male        Master's                 20.0

In [48]:
# normalize our dataset
tf.random.set_seed(42)
ct = make_column_transformer(
    (MinMaxScaler(), ["Age", "Years of Experience"]),
    (OneHotEncoder(handle_unknown='ignore'), ["Gender", "Education Level"])
)

# split our dataset to test and train
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)

# fit the column transformer to our training dataset
ct.fit(x_train)

# tranforming trainig and test with normaliztion and onhotencoder
x_train_normalize = ct.transform(x_train)
x_test_normalize = ct.transform(x_test)

x_train_normalize[0]

array([0.34482759, 0.28      , 0.        , 1.        , 0.        ,
       1.        , 0.        , 0.        , 0.        ])

In [57]:
# let's check our shape
x_train.shape, x_train_normalize.shape

x_train_normalize

array([[0.34482759, 0.28      , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.44827586, 0.4       , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.17241379, 0.08      , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.72413793, 0.64      , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.13793103, 0.04      , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.86206897, 0.76      , 1.        , ..., 1.        , 0.        ,
        0.        ]])

In [59]:
# let's build neural network to feed our data 

# build our model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])

# compile our model

model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=["mae"]
              )

# fit our model

model.fit(x_train_normalize, y_train, epochs=100)

Epoch 1/100
10/10 [==============================] - 2s 4ms/step - loss: nan - mae: nan
Epoch 2/100
10/10 [==============================] - 0s 9ms/step - loss: nan - mae: nan
Epoch 3/100
10/10 [==============================] - 0s 7ms/step - loss: nan - mae: nan
Epoch 4/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 5/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 6/100
10/10 [==============================] - 0s 9ms/step - loss: nan - mae: nan
Epoch 7/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 8/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 9/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 10/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 11/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 12/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 13/100
10/10 [==============================] - 0s 8ms/step - loss: nan - mae: nan
Epoch 14/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 15/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 16/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 17/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 18/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 19/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 20/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 21/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 22/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 23/100
10/10 [==============================] - 0s 8ms/step - loss: nan - mae: nan
Epoch 24/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 25/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 26/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 27/100
10/10 [==============================] - 0s 6ms/step - loss: nan - mae: nan
Epoch 28/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 29/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 30/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 31/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 32/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 33/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 34/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 35/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 36/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 37/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 38/100
10/10 [==============================] - 0s 22ms/step - loss: nan - mae: nan
Epoch 39/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 40/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 41/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 42/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 43/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 44/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 45/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 46/100
10/10 [==============================] - 0s 11ms/step - loss: nan - mae: nan
Epoch 47/100
10/10 [==============================] - 0s 12ms/step - loss: nan - mae: nan
Epoch 48/100
10/10 [==============================] - 0s 6ms/step - loss: nan - mae: nan
Epoch 49/100
10/10 [==============================] - 0s 6ms/step - loss: nan - mae: nan
Epoch 50/100
10/10 [==============================] - 0s 9ms/step - loss: nan - mae: nan
Epoch 51/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 52/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 53/100
10/10 [==============================] - 0s 6ms/step - loss: nan - mae: nan
Epoch 54/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 55/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 56/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 57/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 58/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 59/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 60/100
10/10 [==============================] - 0s 9ms/step - loss: nan - mae: nan
Epoch 61/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 62/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 63/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 64/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 65/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 66/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 67/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 68/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 69/100
10/10 [==============================] - 0s 8ms/step - loss: nan - mae: nan
Epoch 70/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 71/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 72/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 73/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 74/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 75/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 76/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 77/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 78/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 79/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 80/100
10/10 [==============================] - 0s 7ms/step - loss: nan - mae: nan
Epoch 81/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan
Epoch 82/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 83/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 84/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 85/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 86/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 87/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 88/100
10/10 [==============================] - 0s 22ms/step - loss: nan - mae: nan
Epoch 89/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 90/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 91/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 92/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 93/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 94/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 95/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 96/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 97/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 98/100
10/10 [==============================] - 0s 3ms/step - loss: nan - mae: nan
Epoch 99/100
10/10 [==============================] - 0s 4ms/step - loss: nan - mae: nan
Epoch 100/100
10/10 [==============================] - 0s 5ms/step - loss: nan - mae: nan